export const GET_ALL_BODYPARTLIST = "GET_ALL_BODYPARTLIST"
export const GET_ERROR = "GET_ERROR"
export const GET_ALL_EXERCISES= "GET_ALL_EXERCISES"
export const GET_EXERCISES_BY_BODYPART="GET_EXERCISES_BY_BODYPART"
export const GET_EXERCISES_BY_NAME="GET_EXERCISES_BY_NAME"
export const GET_EXERCISES_BY_ID="GET_EXERCISES_BY_ID"
export const GET_ALL_VIDEOS="GET_ALL_VIDEOS"
export const GET_EXERCISES_BY_TARGET="GET_EXERCISES_BY_TARGET"
export const GET_EXERCISES_BY_EQUIPMENT="GET_EXERCISES_BY_EQUIPMENT"



